// Generated by CoffeeScript 1.6.3
(function() {
  var assert, content, filetxt, fs;

  fs = require('fs');

  assert = require('assert');

  filetxt = __dirname + '/file.txt';

  require('../lib/concatify');

  content = fs.readFileSync(filetxt).toString();

  assert(content === 'abc');

}).call(this);
